# Generated by Django 5.0.6 on 2024-06-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcapFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pcap_files/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IDSAlert',
        ),
        migrations.DeleteModel(
            name='NetworkPacket',
        ),
    ]
